{% set goname = "github.com/jesseduffield/lazygit" %}
{% set version = "0.51.1" %}

{% set name = goname.split('/')[-1] %}
{% set pkg_src = ('src/'+goname).replace("/",os.sep) %}

package:
  name: {{ name|lower }}
  version: {{ version|replace("-", "_") }}

source:
  - folder: {{ pkg_src }}
    url: https://github.com/jesseduffield/lazygit/archive/v{{ version }}.tar.gz
    sha256: 467fb3988a375dbfd9288beaae89205d39795a0fd7f156b813d52bbcb57f3506

build:
  number: 0
  script:
    - pushd {{ pkg_src }}
    - go build -ldflags "-s -w" -v -o $PREFIX/bin/lazygit        # [not win]
    - go build -ldflags "-s -w" -v -o %LIBRARY_BIN%\lazygit.exe  # [win]
    - go-licenses save . --save_path ../../../../library_licenses

requirements:
  build:
    - {{ compiler('go') }}
    - go-licenses

test:
  commands:
    - lazygit --help

about:
  home: https://github.com/jesseduffield/lazygit
  license: MIT
  license_family: MIT
  license_file:
    - {{ pkg_src }}/LICENSE
    - library_licenses/
  summary: |
    A simple terminal UI for git commands, written in Go with the gocui library.
  doc_url: https://godoc.org/github.com/jesseduffield/lazygit
  dev_url: https://github.com/jesseduffield/lazygit

extra:
  recipe-maintainers:
    - dbast
